"""AI Document Drafting Service — LLM text generation + ReportLab PDF engine.

This service:
1. Uses the existing LLM fallback pipeline to generate document text
2. Renders final documents as PDFs via ReportLab
3. NEVER stores PDFs — generates into BytesIO, streams to user, discards

Mandatory rules:
- Page 1 always starts with the bold AI disclaimer
- Every page carries the LexIndia footer
- All output is ephemeral (stream-and-forget)
"""

import io
import logging
from datetime import datetime
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT

from app.schemas.draft import (
    DraftGenerateRequest, DocumentType, RentalClauses
)
from app.services.generate_service import _call_llm_with_fallback

logger = logging.getLogger("lexindia.services.draft")

# ── Constants ─────────────────────────────────────────────────────────────

DISCLAIMER_TEXT = (
    "This document was generated by AI for reference purposes only. "
    "It is not a legally certified document. LexIndia makes no warranty "
    "as to its legal validity. Consult a qualified advocate before use."
)

FOOTER_TEXT = "Generated by LexIndia — For reference only. Not a substitute for legal advice."

DOCUMENT_TITLES = {
    DocumentType.LEGAL_NOTICE: "LEGAL NOTICE",
    DocumentType.RTI_APPLICATION: "APPLICATION UNDER THE RIGHT TO INFORMATION ACT, 2005",
    DocumentType.FIR_DRAFT: "FIRST INFORMATION REPORT (DRAFT)",
    DocumentType.RENTAL_AGREEMENT: "RENTAL / LEASE AGREEMENT",
    DocumentType.AFFIDAVIT: "AFFIDAVIT",
}

# ── LLM Prompt Templates ─────────────────────────────────────────────────

_LEGAL_NOTICE_PROMPT = """You are a professional Indian legal document drafter.
Draft a formal Legal Notice based on the details provided.

Structure:
1. Header with "LEGAL NOTICE" title, date, and reference number
2. "To:" block with recipient details
3. "From:" block with sender details  
4. Subject line
5. Body paragraphs:
   - State the facts of the case clearly
   - Reference the applicable law section(s) if provided
   - State the legal consequences of non-compliance
   - Demand specific action and set a deadline (15 days)
6. Closing with sender signature block

Use formal legal English. Be precise and professional.
Return ONLY the document text — no JSON wrapping, no markdown fences."""

_RTI_PROMPT = """You are a professional Indian legal document drafter.
Draft a formal RTI (Right to Information) Application under RTI Act, 2005.

Structure:
1. "To:" block — The Public Information Officer (PIO) at the relevant authority
2. "From:" block with applicant details
3. Subject: "Application under Section 6(1) of the Right to Information Act, 2005"
4. Body: "I, [Name], would like to seek the following information under the RTI Act, 2005:"
5. Numbered list of specific questions/information sought
6. Declaration: "I am an Indian citizen. The prescribed fee of ₹10 is enclosed."
7. Signature block with date

Use formal English. Be specific in the information requested.
Return ONLY the document text — no JSON wrapping, no markdown fences."""

_FIR_PROMPT = """You are a professional Indian legal document drafter.
Draft a First Information Report (FIR) complaint to be filed at a police station.

Structure:
1. "To:" The Station House Officer (SHO) of the relevant police station
2. "From:" Complainant details
3. Subject: "FIR Complaint — [brief description]"
4. Body:
   - Date, time, and place of the incident
   - Detailed narration of the incident in chronological order
   - Names and descriptions of accused persons (if known)
   - Details of witnesses (if any)
   - Reference to applicable IPC sections
   - List of evidence/documents attached
5. Prayer: "I request you to register an FIR and investigate the matter."
6. Declaration: "The above facts are true to the best of my knowledge."
7. Signature block

Use clear, factual language. No opinions.
Return ONLY the document text — no JSON wrapping, no markdown fences."""

_RENTAL_AGREEMENT_PROMPT = """You are a professional Indian legal document drafter.
Draft a Rental/Lease Agreement valid under Indian law.

Structure:
1. Title: "RENTAL / LEASE AGREEMENT"
2. Preamble: "This Rental Agreement is executed on [date] at [city]"
3. Parties: "BETWEEN" Landlord details "AND" Tenant details
4. Property description
5. Terms and Conditions, numbered:
   - Duration and start date
   - Monthly rent amount and due date (1st of each month)
   - Security deposit amount and refund terms
   - Purpose: residential use only
   - Maintenance and upkeep responsibilities
   - Termination: [notice_period] month notice by either party
   - Include any additional clauses marked as enabled
6. Signatures block for both parties and two witnesses

Use formal legal English typical of Indian rental agreements.
Return ONLY the document text — no JSON wrapping, no markdown fences."""

_AFFIDAVIT_PROMPT = """You are a professional Indian legal document drafter.
Draft a general-purpose Affidavit.

Structure:
1. Title: "AFFIDAVIT"
2. "I, [Name], son/daughter of [Father's Name], resident of [Address], do hereby solemnly affirm and declare as follows:"
3. Numbered paragraphs stating the facts
4. "I declare that the above statements are true and correct to the best of my knowledge and belief."
5. "DEPONENT" signature block
6. "VERIFICATION" section: "Verified at [place] on [date]"
7. Space for Notary/Oath Commissioner stamp

Use formal legal English.
Return ONLY the document text — no JSON wrapping, no markdown fences."""

PROMPTS = {
    DocumentType.LEGAL_NOTICE: _LEGAL_NOTICE_PROMPT,
    DocumentType.RTI_APPLICATION: _RTI_PROMPT,
    DocumentType.FIR_DRAFT: _FIR_PROMPT,
    DocumentType.RENTAL_AGREEMENT: _RENTAL_AGREEMENT_PROMPT,
    DocumentType.AFFIDAVIT: _AFFIDAVIT_PROMPT,
}


# ── LLM Draft Generation ─────────────────────────────────────────────────

def _build_user_message(req: DraftGenerateRequest) -> str:
    """Build the user message from the request for the LLM."""
    parts = [f"Document Type: {req.document_type.value}"]

    # Sender
    parts.append(f"\n--- SENDER / APPLICANT ---")
    parts.append(f"Name: {req.sender.full_name}")
    parts.append(f"Address: {req.sender.address}")
    if req.sender.phone:
        parts.append(f"Phone: {req.sender.phone}")
    if req.sender.email:
        parts.append(f"Email: {req.sender.email}")

    # Recipient
    if req.recipient:
        parts.append(f"\n--- RECIPIENT ---")
        parts.append(f"Name: {req.recipient.full_name}")
        parts.append(f"Address: {req.recipient.address}")
        if req.recipient.phone:
            parts.append(f"Phone: {req.recipient.phone}")

    # Law context (from search results)
    if req.act_name or req.law_section_id:
        parts.append(f"\n--- APPLICABLE LAW ---")
        if req.act_name:
            parts.append(f"Act: {req.act_name}")
        if req.law_section_id:
            parts.append(f"Section: {req.law_section_id}")
        if req.section_text:
            parts.append(f"Section Text: {req.section_text[:500]}")

    # Subject / Incident
    parts.append(f"\n--- SUBJECT / INCIDENT ---")
    parts.append(f"Description: {req.subject}")
    if req.incident_date:
        parts.append(f"Date of Incident: {req.incident_date.isoformat()}")
    if req.incident_location:
        parts.append(f"Location: {req.incident_location}")
    if req.desired_outcome:
        parts.append(f"Desired Outcome: {req.desired_outcome}")

    # Rental-specific
    if req.document_type == DocumentType.RENTAL_AGREEMENT and req.rental_details:
        rd = req.rental_details
        parts.append(f"\n--- RENTAL DETAILS ---")
        parts.append(f"Property Address: {rd.property_address}")
        parts.append(f"Monthly Rent: ₹{rd.monthly_rent:,.2f}")
        parts.append(f"Security Deposit: ₹{rd.security_deposit:,.2f}")
        parts.append(f"Start Date: {rd.agreement_start_date.isoformat()}")
        parts.append(f"Duration: {rd.duration_months} months")
        # Clauses
        enabled = []
        if rd.clauses.no_pets_allowed:
            enabled.append("No Pets Allowed: Tenant shall not keep any pets on the premises.")
        if rd.clauses.lock_in_period:
            enabled.append("Lock-in Period: Neither party may terminate the agreement during the first 11 months.")
        if rd.clauses.maintenance_by_tenant:
            enabled.append("Maintenance by Tenant: Tenant is responsible for all minor repairs and routine maintenance.")
        if enabled:
            parts.append(f"\nAdditional Clauses to Include:")
            for c in enabled:
                parts.append(f"  - {c}")

    # Language
    lang_label = "Hindi" if req.language == "hi" else "English"
    parts.append(f"\nDraft Language: {lang_label}")

    return "\n".join(parts)


async def generate_draft_text(req: DraftGenerateRequest) -> str:
    """Generate document text using the LLM fallback pipeline.

    Args:
        req: The validated draft generation request.

    Returns:
        The AI-generated document text as a plain string.

    Raises:
        RuntimeError if all LLM providers fail.
    """
    system_prompt = PROMPTS.get(req.document_type, _LEGAL_NOTICE_PROMPT)
    user_message = _build_user_message(req)

    logger.info(f"Generating {req.document_type.value} draft ({len(user_message)} chars)")

    # The existing fallback function returns parsed JSON, but our prompts
    # ask for plain text.  We call directly through the providers instead.
    from app.services.generate_service import (
        _call_openai, _call_gemini, _call_grok
    )
    from app.config import settings

    for provider in settings.llm_providers:
        try:
            logger.info(f"Attempting draft with {provider.upper()}")

            if provider == "openai" and settings.OPENAI_API_KEY:
                raw = await _call_openai(
                    system_prompt, user_message, response_format="text"
                )
            elif provider == "gemini" and settings.GEMINI_API_KEY:
                raw = await _call_gemini(system_prompt, user_message)
            elif provider == "grok" and settings.GROK_API_KEY:
                raw = await _call_grok(
                    system_prompt, user_message, response_format="text"
                )
            else:
                continue

            if raw and raw.strip():
                logger.info(f"Draft generated successfully via {provider.upper()} ({len(raw)} chars)")
                return raw.strip()

        except Exception as e:
            logger.error(f"{provider.upper()} failed for draft: {e}")
            continue

    # Fallback to mock/template-based generation when no API keys available
    logger.warning("All LLM providers unavailable, using template-based mock generation")
    return _generate_mock_draft(req)


# ── Mock/Template-based Draft Generation ─────────────────────────────────

def _generate_mock_draft(req: DraftGenerateRequest) -> str:
    """Generate a mock legal document using templates when AI APIs are unavailable.
    
    This is used for testing/demo when no valid API keys are configured.
    """
    from datetime import date
    
    if req.document_type == DocumentType.LEGAL_NOTICE:
        return f"""LEGAL NOTICE

Date: {date.today().strftime('%d-%m-%Y')}
Reference No.: LN-{hash(req.sender.full_name) % 10000:04d}

TO:
{req.recipient.full_name if req.recipient else 'Recipient Name'}
{req.recipient.address if req.recipient else 'Recipient Address'}

FROM:
{req.sender.full_name}
{req.sender.address}
Contact: {req.sender.phone or 'Not provided'}

SUBJECT: {req.subject}

Dear Sir/Madam,

This letter serves as a formal Legal Notice regarding the above matter.

FACTS OF THE CASE:
{req.subject}

APPLICABLE LAW:
{f"The matter falls under {req.act_name}, Section {req.law_section_id}." if req.act_name else "The matter involves violation of applicable Indian law."}

LEGAL CONSEQUENCE:
Non-compliance with this notice may result in legal proceedings against you.

DEMAND:
You are hereby required to take necessary action to rectify this matter within 15 (fifteen) days from receipt of this notice.

Dated: {date.today().strftime('%d-%m-%Y')}

Yours faithfully,

{req.sender.full_name}
{req.sender.address}
"""

    elif req.document_type == DocumentType.RTI_APPLICATION:
        return f"""APPLICATION UNDER THE RIGHT TO INFORMATION ACT, 2005

Date: {date.today().strftime('%d-%m-%Y')}

TO:
The Public Information Officer (PIO)
[Government Department/Authority]

FROM:
Name: {req.sender.full_name}
Address: {req.sender.address}
Contact: {req.sender.phone or 'Not provided'}
Email: {req.sender.email or 'Not provided'}

SUBJECT: Application for Information under RTI Act, 2005

Dear Sir/Madam,

I hereby submit this application under Section 6(1) of the Right to Information Act, 2005, requesting the following information:

INFORMATION SOUGHT:
{req.subject}

The information requested is necessary for: Obtaining information about government operations and decisions that affect my rights and interests.

I request the information in the following format: Electronic copy (Email/CD) if available, otherwise hardcopy.

FEE:
I am prepared to pay the prescribed fee for providing this information. Please inform me of the applicable charges.

TIME LIMIT:
As per the RTI Act, the information should be provided within 30 days.

Yours faithfully,

{req.sender.full_name}
Signature: _______________
Date: {date.today().strftime('%d-%m-%Y')}
"""

    elif req.document_type == DocumentType.FIR_DRAFT:
        return f"""FIRST INFORMATION REPORT (DRAFT)

FIR No.: [To be filled by Police]
Police Station: [To be filled by Police]
Date of Complaint: {date.today().strftime('%d-%m-%Y')}

I, {req.sender.full_name}, aged [age], resident of {req.sender.address}, hereby lodge this First Information Report (FIR) against [accused name/details] for committing offence(s) as mentioned hereunder.

INCIDENT DETAILS:
Date of Incident: {req.incident_date or 'As mentioned below'}
Location of Incident: {req.incident_location or 'Not specified'}
Time of Incident: [To be specified]

FACTS OF THE CASE:
{req.subject}

EVIDENCE/WITNESSES:
[To be provided by complainant]

DESIRED OUTCOME:
{req.desired_outcome or 'Action as per law'}

APPLICABLE SECTIONS:
{req.section_text or 'Applicable sections of IPC/other laws as appropriate'}

I hereby declare that the above facts stated are true to my knowledge and belief.

Signature: _______________
Name: {req.sender.full_name}
Date: {date.today().strftime('%d-%m-%Y')}
"""

    elif req.document_type == DocumentType.AFFIDAVIT:
        return f"""AFFIDAVIT

I, {req.sender.full_name}, Son/Daughter of [Father's Name], aged [age], resident of {req.sender.address}, do hereby solemnly affirm and declare as follows:

1. That I am a competent person to make this affidavit and the facts stated herein are within my knowledge and belief.

2. {req.subject}

3. That the above facts are true and correct to the best of my knowledge and belief and I undertake to abide by the consequences of perjury if any statement made herein is found to be false.

Signed and affirmed at [Place] on this {date.today().strftime('%d day of %B, %Y')}.

_______________________
{req.sender.full_name}

Before me,
_______________________
Notary Public / Magistrate
"""

    elif req.document_type == DocumentType.RENTAL_AGREEMENT:
        from app.schemas.draft import RentalDetails
        details: RentalDetails = req.rental_details
        return f"""RENTAL / LEASE AGREEMENT

This Rental Agreement is made and entered into on {date.today().strftime('%d-%m-%Y')} between:

LANDLORD: {req.sender.full_name}
Address: {req.sender.address}
Contact: {req.sender.phone or 'Not provided'}

TENANT: {req.recipient.full_name if req.recipient else 'Tenant Name'}
Address: {req.recipient.address if req.recipient else 'Tenant Address'}
Contact: {req.recipient.phone if req.recipient else 'Not provided'}

PROPERTY DETAILS:
Address: {details.property_address if details else 'Not specified'}
Monthly Rent: ₹{details.monthly_rent if details else '0'}
Security Deposit: ₹{details.security_deposit if details else '0'}

TERMS:
1. The tenancy shall commence from {details.agreement_start_date if details else date.today().strftime('%d-%m-%Y')} for a period of {details.duration_months if details else '11'} month(s).

2. The tenant shall pay rent on or before [date] every month.

3. The security deposit shall be refunded within 30 days of vacating the property, subject to no damages.

4. {'No pets are allowed on the premises.' if details and details.clauses and details.clauses.no_pets_allowed else ''}

5. {'The tenant shall maintain the property and perform routine maintenance.' if details and details.clauses and details.clauses.maintenance_by_tenant else ''}

6. Violation of this agreement may result in eviction proceedings.

SIGNATURES:

Landlord: ________________     Date: ___________
{req.sender.full_name}

Tenant: ________________     Date: ___________
{req.recipient.full_name if req.recipient else 'Tenant Name'}

Witnesses:
1. ________________     2. ________________
"""

    return "Mock document generated. Please configure valid API keys for AI-powered drafting."


# ── PDF Engine (ReportLab) ────────────────────────────────────────────────

def _footer_callback(canvas, doc):
    """Draw the footer on every page — small professional line only."""
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(HexColor("#666666"))
    page_width = A4[0]
    canvas.drawCentredString(
        page_width / 2, 15 * mm,
        FOOTER_TEXT
    )
    # Page number
    canvas.drawRightString(
        page_width - 20 * mm, 15 * mm,
        f"Page {doc.page}"
    )
    canvas.restoreState()


def export_to_pdf(
    draft_text: str,
    document_type: DocumentType,
    title: Optional[str] = None,
) -> io.BytesIO:
    """Render finalized document text as a professionally formatted PDF.

    Returns a BytesIO buffer — never touches the filesystem.

    Args:
        draft_text: The finalized document text.
        document_type: Used for the PDF title if no custom title provided.
        title: Optional custom title.

    Returns:
        io.BytesIO containing the PDF bytes, seeked to position 0.
    """
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=25 * mm,
        bottomMargin=25 * mm,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        title=title or DOCUMENT_TITLES.get(document_type, "Legal Document"),
        author="LexIndia AI",
    )

    styles = getSampleStyleSheet()

    # ── Custom Styles ─────────────────────────────────────────────────
    styles.add(ParagraphStyle(
        "DocTitle",
        parent=styles["Heading1"],
        fontSize=16,
        alignment=TA_CENTER,
        spaceAfter=12,
        textColor=HexColor("#1a1a2e"),
        fontName="Helvetica-Bold",
    ))

    styles.add(ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Helvetica-BoldOblique",
        textColor=HexColor("#cc0000"),
        alignment=TA_JUSTIFY,
        borderWidth=1,
        borderColor=HexColor("#cc0000"),
        borderPadding=8,
        spaceBefore=6,
        spaceAfter=16,
        backColor=HexColor("#fff5f5"),
    ))

    styles.add(ParagraphStyle(
        "DocBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=16,
        alignment=TA_JUSTIFY,
        fontName="Helvetica",
        spaceAfter=6,
    ))

    styles.add(ParagraphStyle(
        "DocDate",
        parent=styles["Normal"],
        fontSize=10,
        alignment=TA_LEFT,
        textColor=HexColor("#555555"),
        spaceAfter=12,
    ))

    # ── Build Story ───────────────────────────────────────────────────
    story = []

    # Date
    story.append(Paragraph(
        f"Date: {datetime.now().strftime('%d %B %Y')}",
        styles["DocDate"]
    ))

    # Title
    doc_title = title or DOCUMENT_TITLES.get(document_type, "LEGAL DOCUMENT")
    story.append(Paragraph(doc_title, styles["DocTitle"]))

    # Horizontal rule
    story.append(HRFlowable(
        width="100%", thickness=1.5, color=HexColor("#1a1a2e"),
        spaceBefore=4, spaceAfter=12
    ))

    # ── Mandatory Disclaimer (Page 1, Bold) ───────────────────────────
    story.append(Paragraph(
        f"<b>⚠ DISCLAIMER:</b> {DISCLAIMER_TEXT}",
        styles["Disclaimer"]
    ))

    story.append(Spacer(1, 8))

    # ── Document Body ─────────────────────────────────────────────────
    # Split the draft text into paragraphs and render each
    paragraphs = draft_text.split("\n")
    for para_text in paragraphs:
        stripped = para_text.strip()
        if not stripped:
            story.append(Spacer(1, 6))
            continue

        # Detect headings (lines in ALL CAPS or starting with numbers like "1.")
        if stripped.isupper() and len(stripped) < 100:
            story.append(Spacer(1, 8))
            story.append(Paragraph(
                f"<b>{stripped}</b>",
                styles["Heading3"]
            ))
        elif stripped.startswith(("---", "___", "===")):
            story.append(HRFlowable(
                width="100%", thickness=0.5, color=HexColor("#cccccc"),
                spaceBefore=4, spaceAfter=4
            ))
        else:
            # Escape XML-sensitive characters for ReportLab
            safe = (
                stripped
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            story.append(Paragraph(safe, styles["DocBody"]))

    # Build the PDF
    doc.build(story, onFirstPage=_footer_callback, onLaterPages=_footer_callback)

    buffer.seek(0)
    logger.info(f"PDF generated: {buffer.getbuffer().nbytes} bytes")
    return buffer
