"""Pydantic schemas for the AI Document Drafting API.

Defines request/response models for:
- Draft text generation (LLM-powered)
- PDF export (streamed, never stored)
- Document type enumeration
"""

from enum import Enum
from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import date


# ── Document Types ────────────────────────────────────────────────────────

class DocumentType(str, Enum):
    """Supported legal document types for AI drafting."""
    LEGAL_NOTICE = "legal_notice"
    RTI_APPLICATION = "rti_application"
    FIR_DRAFT = "fir_draft"
    RENTAL_AGREEMENT = "rental_agreement"
    AFFIDAVIT = "affidavit"


# ── Party Details ─────────────────────────────────────────────────────────

class PartyDetails(BaseModel):
    """Details of a party (sender/recipient/landlord/tenant) in a legal document."""
    full_name: str = Field(..., min_length=2, max_length=200, description="Full legal name.")
    address: str = Field(..., min_length=5, max_length=500, description="Complete address.")
    phone: Optional[str] = Field(None, max_length=15, description="Phone number (optional).")
    email: Optional[str] = Field(None, max_length=100, description="Email address (optional).")


# ── Rental Agreement Clauses ──────────────────────────────────────────────

class RentalClauses(BaseModel):
    """Three fixed toggleable clauses for rental agreements."""
    no_pets_allowed: bool = Field(default=False, description="Include 'No Pets Allowed' clause.")
    lock_in_period: bool = Field(default=False, description="Include '11-month lock-in period' clause.")
    maintenance_by_tenant: bool = Field(default=False, description="Include 'Maintenance by Tenant' clause.")


# ── Rental Agreement Specifics ────────────────────────────────────────────

class RentalDetails(BaseModel):
    """Fields specific to rental agreement generation."""
    property_address: str = Field(..., min_length=5, max_length=500, description="Full address of the rental property.")
    monthly_rent: float = Field(..., gt=0, description="Monthly rent amount in INR.")
    security_deposit: float = Field(..., ge=0, description="Security deposit amount in INR.")
    agreement_start_date: date = Field(..., description="Start date of the agreement.")
    duration_months: int = Field(default=11, ge=1, le=60, description="Duration in months.")
    clauses: RentalClauses = Field(default_factory=RentalClauses, description="Optional toggleable clauses.")


# ── Draft Generation Request ─────────────────────────────────────────────

class DraftGenerateRequest(BaseModel):
    """Request body for POST /api/draft/generate."""

    document_type: DocumentType = Field(
        ..., description="Type of legal document to generate."
    )
    sender: PartyDetails = Field(
        ..., description="Details of the person sending/filing the document."
    )
    recipient: Optional[PartyDetails] = Field(
        None, description="Details of the recipient (not needed for affidavits)."
    )

    # Context from search results (optional — pre-fills from LawCard)
    law_section_id: Optional[str] = Field(
        None, description="Section ID from search results (e.g. IPC-420)."
    )
    act_name: Optional[str] = Field(
        None, description="Name of the Act for context."
    )
    section_text: Optional[str] = Field(
        None, description="Original section text for reference."
    )

    # Incident / Subject details
    subject: str = Field(
        ..., min_length=10, max_length=2000,
        description="Plain-language description of the issue or subject."
    )
    incident_date: Optional[date] = Field(
        None, description="Date of the incident (if applicable)."
    )
    incident_location: Optional[str] = Field(
        None, max_length=300, description="Location of the incident."
    )
    desired_outcome: Optional[str] = Field(
        None, max_length=500,
        description="What the user wants to achieve (e.g. 'refund of ₹50,000')."
    )

    # Rental-specific (only used when document_type == rental_agreement)
    rental_details: Optional[RentalDetails] = Field(
        None, description="Required when document_type is 'rental_agreement'."
    )

    # Language
    language: str = Field(
        default="en",
        pattern="^(en|hi)$",
        description="Draft language: en (English) or hi (Hindi)."
    )


# ── Draft Generation Response ────────────────────────────────────────────

class DraftGenerateResponse(BaseModel):
    """Response body for POST /api/draft/generate."""

    document_type: DocumentType
    draft_text: str = Field(
        ..., description="AI-generated document text in markdown format."
    )
    language: str
    disclaimer: str = Field(
        default=(
            "This document was generated by AI for reference purposes only. "
            "It is not a legally certified document. LexIndia makes no warranty "
            "as to its legal validity. Consult a qualified advocate before use."
        ),
        description="Mandatory legal disclaimer."
    )


# ── PDF Export Request ───────────────────────────────────────────────────

class DraftExportRequest(BaseModel):
    """Request body for POST /api/draft/export — converts finalized text to PDF."""

    document_type: DocumentType = Field(
        ..., description="Type of document (used for PDF title)."
    )
    draft_text: str = Field(
        ..., min_length=50,
        description="The finalized document text to render as PDF."
    )
    title: Optional[str] = Field(
        None, max_length=200,
        description="Custom title for the PDF header. Auto-generated if omitted."
    )
