"""lawyer_mode

Revision ID: 3ee00c1dd27a
Revises: 001_initial_schema
Create Date: 2026-04-12 18:28:52.832120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee00c1dd27a'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laws', sa.Column('cross_references', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('laws', sa.Column('amendment_note', sa.Text(), nullable=True))
    op.add_column('query_logs', sa.Column('mode', sa.String(length=10), server_default='citizen', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'mode')
    op.drop_column('laws', 'amendment_note')
    op.drop_column('laws', 'cross_references')
    # ### end Alembic commands ###
